version: "3.8"
networks:
  local_network_docker_php_8_3:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.16.236.0/24
services: 
  mysql:
    image: mysql:8.3
    container_name: docker-mysql-php8-3
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    working_dir: /var/lib/mysql
    volumes: 
      - ./conf/mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql:/var/lib/mysql:delegated
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_TCP_PORT: 3306
    networks: 
      - local_network_docker_php_8_3
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-php8-3
    volumes: 
        - ./src:/var/www/html
        - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - local_network_docker_php_8_3